version: '3.7'

volumes:
    db_data:

services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'

        networks:
        - stock-ml-network-intern

        command: --init-file /docker-entrypoint-initdb.d/init.sql

        volumes:
            - db_data:/var/lib/mysql
            - ./stock-ml-db/init.sql:/docker-entrypoint-initdb.d/init.sql

    web:
        build: stock-ml-web/.
        ports:
            - "8000:8000"
        networks:
        - stock-ml-network-intern
        volumes:
          - ./stock-ml-web/stock-ml-web/db.sqlite3:/app/db.sqlite3

    configservice:
        build: stock-ml-config/.
        ports:
            - "5000:5000"
        networks:
        - stock-ml-network-intern

    data:
        build: stock-ml-data/.
        networks:
        - stock-ml-network-intern

    nn:
        build: stock-ml-nn/.
        networks:
        - stock-ml-network-intern

networks:
    stock-ml-network-intern:
