version: '3.7'

volumes:
    db_data:

services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'

        command: --init-file /docker-entrypoint-initdb.d/init.sql

        volumes:
            - db_data:/var/lib/mysql
            - ./stock-ml-db/init.sql:/docker-entrypoint-initdb.d/init.sql

    web:
        build: stock-ml-web/.
        ports:
            - "8000:8000"
        networks:
        - stock-ml-network-extern
        - stock-ml-network-intern

networks:
    stock-ml-network-extern:
        driver: bridge
    stock-ml-network-intern:
