apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  strategy: {}
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: localhost
          image: stock-ml_data
          imagePullPolicy: Never
          name: data
          resources: {}
      restartPolicy: Always
status: {}
